"""add role to users

Revision ID: 75f1c5bce632
Revises: e013e0e67efc
Create Date: 2026-08-17 19:41:13.940495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75f1c5bce632'
down_revision: Union[str, Sequence[str], None] = 'e013e0e67efc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    role_enum = sa.Enum('USER', 'ADMIN', name='userrole')
    role_enum.create(op.get_bind(), checkfirst=True)

    op.add_column(
        'users',
        sa.Column('role', sa.Enum('USER', 'ADMIN', name='userrole'), nullable=False, server_default='USER')
    )
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')

    role_enum = sa.Enum('USER', 'ADMIN', name='userrole')
    role_enum.create_type = False
    role_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
